#:schema node_modules/wrangler/config-schema.json
name = "hyphalbase"
main = "src/index.ts"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[durable_objects.bindings]]
name = "HYPHAL_OBJECT"
class_name = "HyphalObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["HyphalObject"]
