name: Build

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache Rust dependencies and build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check if embeddings-server binary exists
        id: check-binary
        run: |
          if [ -f "target/debug/embeddings-server" ]; then
            echo "Binary exists, skipping build"
            echo "binary_exists=true" >> $GITHUB_OUTPUT
          else
            echo "Binary does not exist, will build"
            echo "binary_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Build embeddings-server
        if: steps.check-binary.outputs.binary_exists != 'true'
        run: cargo build --package embeddings-server

      - name: Start embeddings-server in background
        run: |
          cd target/debug
          ./embeddings-server &
          echo "Waiting for embeddings-server to start..."
          sleep 5  # Give the server time to start

      - name: Run tests
        run: pnpm test
        env:
          OPENAI_API_ENDPOINT: 'http://localhost:8080/v1'
